# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod ‘OneSignal’, ‘>= 2.5.2’, ‘<3.0’
  use_frameworks!

  # Pods for OneSignalNotificationServiceExtension

end

target 'Ping!' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod ‘OneSignal’, ‘>= 2.5.2’, ‘<3.0’
  pod ‘SideMenu’

  # Pods for Ping!

  target 'Ping!Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ping!UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
